
services:
  jet:
    image: ghcr.io/serlithnetwork/jet
    container_name: jet
    expose:
      - "9420"
    volumes:
      - jet_pictures:/opt/jet/pictures
      - jet_config:/opt/jet/config
    environment:
      - JET_DATABASE_URL=r2dbc:postgresql://postgres_container:5432/flare
      - JET_DATABASE_USER=jet
      - JET_DATABASE_PASSWORD=
      - JET_MAX_REQUEST_SIZE=50KB
      - JET_CLEANUP_DAYS=30
      - JET_THUMBNAIL_WORKER_THREADS=2

volumes:
  jet_pictures: {}
  jet_config: {}
